// Serves the arena challenge assets embedded in the worker.
//
// GET /arena-data/<file> returns the byte content of the matching row
// in ARENA_ASSETS (see src/arena-embed.ts, autogenerated by
// scripts/gen-arena-data.mjs). Anything not in the map is 404 with a
// plain JSON error.
//
// Assets are safe-to-cache: they are deterministic and immutable
// between regenerations.

import { ARENA_ASSETS } from "./arena-embed.js";
import { error } from "./util.js";

export function handleArenaAsset(path: string): Response {
  const name = path.slice("/arena-data/".length);
  if (!name || name.includes("/") || name.includes("..")) {
    return error(404, `no arena asset '${name}'`);
  }
  const asset = ARENA_ASSETS.get(name);
  if (!asset) return error(404, `no arena asset '${name}'`);
  return new Response(asset.body, {
    status: 200,
    headers: {
      "content-type": asset.contentType,
      "cache-control": "public, max-age=3600, immutable",
      "x-arena-asset": asset.name,
    },
  });
}

export function handleArenaIndex(): Response {
  const items = [...ARENA_ASSETS.values()].map((a) => ({
    name: a.name,
    content_type: a.contentType,
    bytes: a.body.length,
  }));
  return new Response(JSON.stringify({ assets: items }, null, 2), {
    status: 200,
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "public, max-age=300",
    },
  });
}
